sudo: required

language: generic

servicse:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t junsung/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true junsung/docker-react-app npm run test -- --coverage


after_success:
  - echo "Test Success "